# Generated by Django 6.0.6 on 2026-06-21 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasewatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtoken',
            name='token_hash',
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Enter a valid SHA-256 hex digest.',
                        regex='^[0-9a-fA-F]{64}$',
                    )
                ],
            ),
        ),
    ]
