# Generated by Django 6.0.6 on 2026-06-21 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releasewatch", "0002_alter_feedtoken_token_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mbid", models.UUIDField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("sort_name", models.CharField(blank=True, max_length=255)),
                ("disambiguation", models.CharField(blank=True, max_length=255)),
                ("artist_type", models.CharField(blank=True, max_length=64)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_name", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="releasewatc_name_702e8f_idx"),
                    models.Index(fields=["sort_name"], name="releasewatc_sort_na_198611_idx"),
                    models.Index(
                        fields=["last_refreshed_at"], name="releasewatc_last_re_f2ef19_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("lastfm", "Last.fm"),
                            ("listenbrainz", "ListenBrainz"),
                            ("plain_text", "Plain text"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("pending_review", "Pending review"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=32,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_identifier", models.CharField(blank=True, max_length=255)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("ignored", "Ignored"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="releasewatch.artist",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="releasewatch.importrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sort_name", models.CharField(blank=True, max_length=255)),
                ("locale", models.CharField(blank=True, max_length=16)),
                ("alias_type", models.CharField(blank=True, max_length=64)),
                ("primary", models.BooleanField(default=False)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="releasewatch.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["locale", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artist", "name", "locale"),
                        name="artist_alias_unique_artist_name_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_ignored", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="releasewatch.artist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_ignored"], name="releasewatc_user_id_18c56d_idx"
                    ),
                    models.Index(fields=["artist"], name="releasewatc_artist__c7aa6f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "artist"), name="follow_unique_user_artist"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(
                fields=["user", "source", "status"], name="releasewatc_user_id_7f1752_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrun",
            index=models.Index(fields=["created_at"], name="releasewatc_created_293562_idx"),
        ),
        migrations.AddIndex(
            model_name="importcandidate",
            index=models.Index(
                fields=["import_run", "review_state"], name="releasewatc_import__9dc0b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importcandidate",
            index=models.Index(fields=["source_identifier"], name="releasewatc_source__6bfe75_idx"),
        ),
        migrations.AddConstraint(
            model_name="importcandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_identifier", ""), _negated=True),
                fields=("import_run", "source_identifier"),
                name="import_candidate_unique_run_identifier",
            ),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(fields=["code"], name="releasewatc_code_fac0d6_idx"),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(fields=["expires_at"], name="releasewatc_expires_461cec_idx"),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_uses__gte", 1)), name="invite_max_uses_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(("uses__gte", 0)), name="invite_uses_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(("uses__lte", models.F("max_uses"))),
                name="invite_uses_lte_max_uses",
            ),
        ),
    ]
