# Generated by Django 6.0.6 on 2026-06-21 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releasewatch", "0003_invites_artists_imports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mbid", models.UUIDField(unique=True)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "release_date_precision",
                    models.CharField(
                        blank=True,
                        choices=[("year", "Year"), ("month", "Month"), ("day", "Day")],
                        max_length=8,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=64)),
                ("media_format", models.CharField(blank=True, max_length=64)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mbid", models.UUIDField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("primary_type", models.CharField(blank=True, max_length=64)),
                ("secondary_types", models.JSONField(blank=True, default=list)),
                ("first_release_date", models.DateField(blank=True, null=True)),
                (
                    "first_release_precision",
                    models.CharField(
                        blank=True,
                        choices=[("year", "Year"), ("month", "Month"), ("day", "Day")],
                        max_length=8,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_groups",
                        to="releasewatch.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["artist__sort_name", "first_release_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=2)),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        blank=True,
                        choices=[("year", "Year"), ("month", "Month"), ("day", "Day")],
                        max_length=8,
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                ("notifiable", models.BooleanField(default=True)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="releasewatch.release",
                    ),
                ),
                (
                    "release_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="releasewatch.releasegroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="release",
            name="release_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="releasewatch.releasegroup",
            ),
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("releases", "Releases"),
                            ("cover_art", "Cover art"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_states",
                        to="releasewatch.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("verification", "Verification"),
                            ("password_reset", "Password reset"),
                            ("digest", "Digest"),
                            ("instant", "Instant"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "message_type", "created_at"],
                        name="releasewatc_user_id_3d640a_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="releasewatc_status_5f4b43_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cadence_bucket", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "release_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="releasewatch.releaseevent"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "status"], name="releasewatc_user_id_a93ac0_idx"),
                    models.Index(
                        fields=["cadence_bucket", "status"], name="releasewatc_cadence_d1b492_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "release_event", "cadence_bucket"),
                        name="notification_unique_user_event_bucket",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="releasegroup",
            index=models.Index(fields=["artist", "title"], name="releasewatc_artist__7df93d_idx"),
        ),
        migrations.AddIndex(
            model_name="releasegroup",
            index=models.Index(
                fields=["first_release_date"], name="releasewatc_first_r_d655b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releasegroup",
            index=models.Index(fields=["last_refreshed_at"], name="releasewatc_last_re_eefe2b_idx"),
        ),
        migrations.AddIndex(
            model_name="releaseevent",
            index=models.Index(
                fields=["event_date", "date_precision"], name="releasewatc_event_d_b49ad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="releaseevent",
            index=models.Index(
                fields=["visible", "notifiable"], name="releasewatc_visible_295557_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="releaseevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("release__isnull", False)),
                fields=("release_group", "release", "country"),
                name="release_event_unique_group_release_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="releaseevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("release__isnull", True)),
                fields=("release_group", "country"),
                name="release_event_unique_group_country_no_release",
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["release_group", "country"], name="releasewatc_release_1359ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["release_date"], name="releasewatc_release_470c71_idx"),
        ),
        migrations.AddIndex(
            model_name="syncstate",
            index=models.Index(
                fields=["sync_type", "status"], name="releasewatc_sync_ty_9f8944_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncstate",
            index=models.Index(fields=["retry_after"], name="releasewatc_retry_a_584555_idx"),
        ),
        migrations.AddConstraint(
            model_name="syncstate",
            constraint=models.UniqueConstraint(
                fields=("artist", "sync_type"), name="sync_state_unique_artist_type"
            ),
        ),
    ]
