# Generated by Django 6.0.6 on 2026-06-22 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasewatch', '0004_releases_notifications_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[('lastfm', 'Last.fm'), ('listenbrainz', 'ListenBrainz')],
                        max_length=32,
                    ),
                ),
                ('external_username', models.CharField(max_length=255)),
                ('token_encrypted', models.TextField(blank=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('revoked', 'Revoked'),
                            ('failed', 'Failed'),
                        ],
                        default='active',
                        max_length=16,
                    ),
                ),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['user', 'provider'],
                        name='releasewatc_user_id_7e8d90_idx',
                    ),
                    models.Index(
                        fields=['provider', 'status'],
                        name='releasewatc_provide_aaa3a9_idx',
                    ),
                    models.Index(
                        fields=['last_imported_at'],
                        name='releasewatc_last_im_16d5af_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('status', 'active')),
                        fields=('user', 'provider', 'external_username'),
                        name='provider_account_unique_user_provider_username',
                    )
                ],
            },
        ),
    ]
