# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releasewatch", "0005_provider_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="include_albums",
            field=models.BooleanField(default=True, verbose_name="Albums"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="include_singles",
            field=models.BooleanField(default=True, verbose_name="Singles"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="include_eps",
            field=models.BooleanField(default=True, verbose_name="EPs"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="include_live",
            field=models.BooleanField(default=True, verbose_name="Live releases"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="include_compilations",
            field=models.BooleanField(default=True, verbose_name="Compilations"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="include_remixes",
            field=models.BooleanField(default=True, verbose_name="Remixes"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="include_other_release_types",
            field=models.BooleanField(default=True, verbose_name="Other release types"),
        ),
    ]
