# Generated by Django 6.0.6 on 2026-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasewatch', '0006_notification_type_filters'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='releaseevent',
            index=models.Index(
                fields=['visible', 'updated_at'],
                name='releasewatc_visible_f2528d_idx',
            ),
        ),
    ]
